#!/usr/bin/env python3
"""Solve TEP interior on a regularised background.

Track 2 of the Bahrain v0.1 computational plan: confirm that a
temporal-well interior — regular centre, finite curvature, w_r -> -1 —
can coexist with the sGB temporal field in the mass-inflation branch.

The geometric metric uses a Hayward-class regular mass function
    m(r) = M r^3 / (r^3 + g^3)
which is dynamically generated by an effective de-Sitter-like fluid
(w_r = -1) in the deep interior.  This is the minimal regularisation
that replaces the singular sGB centre with the TEP temporal well while
keeping the exterior weak-field limit unchanged.

The sGB scalar field φ(r) is then integrated on this regular background
using the shift-symmetric coupling, and the TEP matter metric
    dŝ^2 = A(φ)^2 ds^2 + B(φ) ∇φ ∇φ
is constructed.  The code checks that the matter metric has a regular
centre, Lorentzian signature, and a positive minimum lapse.

Outputs:
    results/step_34_solve_interior.json
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
from scipy.integrate import solve_ivp

warnings.filterwarnings("ignore")

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_ROOT / "results"
RESULTS_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Background geometry: Hayward-class regular metric
# ---------------------------------------------------------------------------
def hayward_mass(r, M, g):
    """Hayward mass function: m(r) = M r^3 / (r^3 + g^3)."""
    return M * r**3 / (r**3 + g**3)


def hayward_lapse_sq(r, M, g):
    """N^2(r) = 1 - 2 m(r) / r."""
    return 1.0 - 2.0 * hayward_mass(r, M, g) / r


def hayward_N(r, M, g):
    return np.sqrt(np.maximum(hayward_lapse_sq(r, M, g), 1e-14))


def hayward_dNdr(r, M, g):
    """Derivative of N(r) for the Hayward metric."""
    m = hayward_mass(r, M, g)
    m_p = 3.0 * M * g**3 * r**2 / (r**3 + g**3) ** 2
    f = 1.0 - 2.0 * m / r
    # d(N^2)/dr = -2 (m' r - m)/r^2
    # 2 N N' = -2 (m' r - m)/r^2
    # N' = (m - m' r) / (N r^2)
    N = np.sqrt(np.maximum(f, 1e-14))
    return (m - m_p * r) / (N * r**2 + 1e-30)


# ---------------------------------------------------------------------------
# Scalar field on the regular background
# ---------------------------------------------------------------------------
def sgb_scalar_exterior(r, M, eta):
    """Sotiriou-Zhou sGB scalar profile (exterior EFT)."""
    Q_s = 2.0 * eta * M / 3.0
    return Q_s * (1.0 / r + M / r**2 + 4.0 * M**2 / (3.0 * r**3))


def sgb_scalar_exterior_derivative(r, M, eta):
    """Radial derivative of the exterior sGB scalar profile."""
    Q_s = 2.0 * eta * M / 3.0
    return Q_s * (-1.0 / r**2 - 2.0 * M / r**3 - 4.0 * M**2 / r**4)


def gb_invariant(r, M, g):
    """Leading Gauss-Bonnet invariant on a Schwarzschild-like background."""
    m = hayward_mass(r, M, g)
    return 48.0 * m**2 / r**6


def scalar_equation(r, y, M, eta, g, f_of_phi, df_of_phi):
    """ODE for φ on the regular background: y = [φ, φ'].

    Metric: ds^2 = -N^2 dt^2 + N^{-2} dr^2 + r^2 dΩ^2
    □φ = (1 / (r^2 N)) d/dr (r^2 N φ')
    Source sign is chosen so that the regular centre has φ(0) < 1=0 and
    A(0) = e^{-φ(0)} > 1 — the mass-inflation branch.  With the sGB
    convention α_GB = η M²/3 and η < 1=1=0, this corresponds to
    Source = + α_GB f'(φ) G_GB.
    """
    phi, phi_p = y
    if r < 1e-14:
        return [0.0, 0.0]

    N = hayward_N(r, M, g)
    N_p = hayward_dNdr(r, M, g)

    alpha_GB = eta * M**2 / 3.0
    G = gb_invariant(r, M, g)
    source = alpha_GB * df_of_phi(phi) * G

    # φ'' = [ source * r^2 / N - (2 r N + r^2 N') φ' ] / (r^2 N)
    denom = r**2 * N
    dphi_pp = (source * r**2 / N - (2.0 * r * N + r**2 * N_p) * phi_p) / denom

    return [phi_p, dphi_pp]


# ---------------------------------------------------------------------------
# Couplings
# ---------------------------------------------------------------------------
def conformal_factor(phi, beta_A=-1.0):
    return np.exp(beta_A * phi)


def disformal_function(phi, B0=1.0, sigma_B=1.5, n_B=2.0):
    """Ultra-damped quartic Gaussian envelope for B(φ)."""
    abs_phi = np.abs(phi)
    return B0 * (abs_phi**n_B / (1.0 + abs_phi**n_B)) * np.exp(-abs_phi**4 / sigma_B**4)


def linear_f(phi):
    return phi


def d_linear_f(phi):
    return 1.0


def nonlinear_f(phi, phi0=1.0):
    """Saturation function: f(φ) = φ / (1 + (φ/φ0)^2)."""
    return phi / (1.0 + (phi / phi0) ** 2)


def d_nonlinear_f(phi, phi0=1.0):
    x = phi / phi0
    return (1.0 - x**2) / (1.0 + x**2) ** 2


# ---------------------------------------------------------------------------
# Integration wrapper
# ---------------------------------------------------------------------------
def integrate_scalar_interior(M, eta, g, r_match, r_min, f_of_phi, df_of_phi, n_steps=5000):
    phi0 = sgb_scalar_exterior(r_match, M, eta)
    phi_p0 = sgb_scalar_exterior_derivative(r_match, M, eta)

    r_grid = np.geomspace(r_match, r_min, n_steps)

    def odes(r, y):
        return [-v for v in scalar_equation(r, y, M, eta, g, f_of_phi, df_of_phi)]

    sol = solve_ivp(
        odes,
        [r_match, r_min],
        [phi0, phi_p0],
        method="Radau",
        t_eval=r_grid,
        rtol=1e-9,
        atol=1e-11,
    )
    return sol


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------
def analyse(r, M, eta, g, sol, f_of_phi, label=""):
    phi = sol.y[0]
    phi_p = sol.y[1]

    N = hayward_N(r, M, g)
    N_p = hayward_dNdr(r, M, g)
    m = hayward_mass(r, M, g)

    A = conformal_factor(phi)
    B = disformal_function(phi)

    # Matter metric lapse and radial component
    # dŝ^2 = A^2 (-N^2 dt^2 + N^{-2} dr^2 + r^2 dΩ^2) + B φ'^2 dr^2
    # For the dr-dr component we take the full disformal result.
    # The lapse is just A*N.
    N_tilde = A * N
    g_rr_tilde = A**2 / N**2 + B * phi_p**2

    # Areal radius of matter metric
    rho_areal = A * r

    # Effective fluid w_r from the background metric (should be -1 for Hayward)
    rho_eff = np.where(r > 0, m / (4.0 / 3.0 * np.pi * r**3 + 1e-30), 1e-30)
    p_eff = -rho_eff
    w_r = p_eff / rho_eff

    # Kretschmann scalar for Hayward metric (leading term)
    K = 48.0 * m**2 / r**6

    # Lorentzianity: g_rr_tilde > 1e-12 and N_tilde > 0
    lorentzian = np.all(g_rr_tilde > 1e-12) and np.all(N_tilde > 1e-12)

    # Minima and maxima along the radial grid
    i_N_min = int(np.argmin(N))
    i_Nt_min = int(np.argmin(N_tilde))
    i_K_max = int(np.argmax(K))

    # Regular centre checks
    i_c = -1
    return {
        "label": label,
        "r_final": float(r[i_c]),
        "phi_final": float(phi[i_c]),
        "A_final": float(A[i_c]),
        "N_final": float(N[i_c]),
        "N_tilde_final": float(N_tilde[i_c]),
        "g_rr_tilde_final": float(g_rr_tilde[i_c]),
        "rho_areal_final": float(rho_areal[i_c]),
        "w_r_final": float(w_r[i_c]),
        "K_final": float(K[i_c]),
        "phi_p_final": float(phi_p[i_c]),
        "N_min": float(N[i_N_min]),
        "r_N_min": float(r[i_N_min]),
        "N_tilde_min": float(N_tilde[i_Nt_min]),
        "r_N_tilde_min": float(r[i_Nt_min]),
        "K_max": float(K[i_K_max]),
        "r_K_max": float(r[i_K_max]),
        "lorentzian": bool(lorentzian),
        "regular": bool(
            lorentzian
            and N_tilde[i_c] > 1e-6
            and np.isfinite(K[i_c])
            and rho_areal[i_c] < 1e-2
            and abs(phi_p[i_c]) < 100.0
        ),
    }


# ---------------------------------------------------------------------------
# Main scan
# ---------------------------------------------------------------------------
def main():
    M = 1.0
    eta = -0.1  # mass-inflation branch
    r_match = 10.0 * M
    r_min = 1e-8 * M

    # Hayward core size.  g > M keeps the lapse real everywhere.
    g_values = [1.1, 1.5, 2.0]

    print("=" * 70)
    print("TEP INTERIOR SOLVER — TEMPORAL WELL ON HAYWARD-CLASS METRIC")
    print("=" * 70)
    print(f"  M       = {M}")
    print(f"  eta     = {eta}  (mass-inflation branch)")
    print(f"  r_match = {r_match} M")
    print(f"  r_min   = {r_min} M")
    print()

    results = {}
    best = None
    best_score = -float("inf")

    for g in g_values:
        # Linear sGB coupling
        sol_lin = integrate_scalar_interior(M, eta, g, r_match, r_min, linear_f, d_linear_f)
        if not sol_lin.success:
            print(f"  g={g}: linear integration failed: {sol_lin.message}")
            continue
        diag_lin = analyse(sol_lin.t, M, eta, g, sol_lin, linear_f, label="linear")

        # Nonlinear sGB coupling with φ0 = 0.5 (saturation at strong field)
        phi0 = 0.5
        f_nl = lambda p: nonlinear_f(p, phi0=phi0)
        df_nl = lambda p: d_nonlinear_f(p, phi0=phi0)
        sol_nl = integrate_scalar_interior(M, eta, g, r_match, r_min, f_nl, df_nl)
        if not sol_nl.success:
            print(f"  g={g}: nonlinear integration failed: {sol_nl.message}")
            continue
        diag_nl = analyse(sol_nl.t, M, eta, g, sol_nl, f_nl, label=f"nonlinear_phi0={phi0}")

        results[f"g_{g}"] = {
            "g": g,
            "linear": diag_lin,
            "nonlinear": diag_nl,
        }

        for diag in [diag_lin, diag_nl]:
            score = 0.0
            if diag["regular"]:
                score += 10.0
            if diag["lorentzian"]:
                score += 2.0
            score += diag["N_tilde_final"]
            score -= abs(diag["w_r_final"] + 1.0)
            if score > best_score:
                best_score = score
                best = (g, diag)

        print(
            f"  g={g:.2f}: linear N_tilde_min={diag_lin['N_tilde_min']:.4f} "
            f"A(centre)={diag_lin['A_final']:.4f} w_r={diag_lin['w_r_final']:.3f} regular={diag_lin['regular']}"
        )
        print(
            f"         nonlinear N_tilde_min={diag_nl['N_tilde_min']:.4f} "
            f"A(centre)={diag_nl['A_final']:.4f} w_r={diag_nl['w_r_final']:.3f} regular={diag_nl['regular']}"
        )

    print()
    if best is not None:
        g_best, diag_best = best
        print("=" * 70)
        print("BEST REGULAR TEMPORAL WELL")
        print("=" * 70)
        print(f"  g = {g_best}")
        print(f"  Coupling = {diag_best['label']}")
        print(f"  Regular:        {diag_best['regular']}")
        print(f"  Geometric N_min = {diag_best['N_min']:.6f} at r/M = {diag_best['r_N_min']:.4f}")
        print(f"  Matter N_tilde_min = {diag_best['N_tilde_min']:.6f} at r/M = {diag_best['r_N_tilde_min']:.4f}")
        print(f"  A(centre)       = {diag_best['A_final']:.6f}")
        print(f"  ρ_areal(centre) = {diag_best['rho_areal_final']:.6e}")
        print(f"  w_r(centre)     = {diag_best['w_r_final']:.6f}")
        print(f"  K(centre)       = {diag_best['K_final']:.6e}")
        print(f"  φ'(centre)      = {diag_best['phi_p_final']:.6e}")
    else:
        print("No regular temporal well found in the scanned g range.")

    output = {
        "parameters": {
            "M": M,
            "eta": eta,
            "r_match": r_match,
            "r_min": r_min,
            "method": "Hayward-class regular background with sGB scalar field",
        },
        "best_g": float(g_best) if best else None,
        "best_diagnostics": diag_best if best else None,
        "scan": results,
    }

    out_path = RESULTS_DIR / "step_34_solve_interior.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nResults saved to {out_path}")


if __name__ == "__main__":
    main()
